#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Thomas Wegmüller

# Short bio or description (displayed in the header)
description: No desc
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one